#!/usr/bin/python
#
# deREferencing - by @danigargu
#

ARROW_SYMBOL      = "→"
MIN_STRING_LENGTH = 3
MAX_STRING_LENGTH = 50
MAX_DEREF_LEVELS  = 2
DEREF_LIMIT       = 20
FLAGS_WIDTH       = 70
SHOW_LEGEND       = True
SHOW_AREA_NAME    = True
SHOW_RETURN_ADDR  = True
HIGHLIGHT_CHANGES = True
HIGHLIGHT_COLOR   = 0xFFD073
STACK_ENTRIES     = 150
PARSE_CALL_ARGS   = True
PAUSE_DBGHOOKS    = False
